version: '3'

services:
  minio:
    container_name: minio
    image: minio/minio
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9001" --address ":9000" /data

  fake-news-classifier:
    image: fake_news_classificator:latest
    container_name: fake-news-classfier
    volumes:
      - ./data:/app/data
      - ./tmp/result:/app/result

volumes:
  minio_storage:
